service: scrape-deals

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/*"

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

functions:
  scrape:
    handler: handler.scrape
    events:
      - schedule: rate(1 minute)